server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&serverTimeZone=CTT
    username: root
    password: Zxy1998.
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent-output: true
    time-zone: GMT+8
  #  redis:
#    database: 9
#    host: 127.0.0.1
#    port: 6379
#    jedis:
#      pool:
#        max-active: 100
#        max-idle: 100
#        min-idle: 10
#        max-wait: 1000ms
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    club:
      msecret:
        mblog:
          mapper: debug
